<?xml version="1.0"?>
<robot name="staggerlite_essential" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- Defining the colors used in this robot -->
  <material name="Black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>

  <material name="White">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>

  <material name="Red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <material name="Green">
    <color rgba="0.0 0.8 0.0 1.0"/>
  </material>

  <material name="Blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>

  <!-- PROPERTY LIST -->
  <!--All units in m-kg-s-radians unit system -->
  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="M_PI_2" value="1.570796327" />
  <xacro:property name="DEG_TO_RAD" value="0.017453293" />

  <!-- Body -->
  <xacro:property name="base_length" value="0.24" /> <!--m-->
  <xacro:property name="base_width" value="0.20" /> 
  <xacro:property name="base_height" value="0.02" /> 
  <xacro:property name="base_mass" value="5" /> <!--kg-->

  <!-- Wheels -->
  <xacro:property name="wheel_diameter" value="0.073" /> 
  <xacro:property name="wheel_radius" value="0.0365" />
  <xacro:property name="wheel_height" value="0.035" />
  <xacro:property name="wheel_mass" value="0.25" />
  <xacro:property name="wheel_spacing" value="0.173" />

  <!-- Caster -->
  <xacro:property name="caster_height" value="0.04" />
  <xacro:property name="caster_diameter" value="0.02" /> 
  <xacro:property name="caster_radius" value="0.01" /> 
  <xacro:property name="caster_mass" value="0.1" />

  <!-- IMU -->
  <xacro:property name="imu_length" value="0.02" /> <!--m-->
  <xacro:property name="imu_width" value="0.02" /> 
  <xacro:property name="imu_height" value="0.01" /> 
  <xacro:property name="imu_mass" value="0.01" /> <!--kg-->

  <!-- Lidar -->
  <xacro:property name="lidar_diameter" value="0.05" /> 
  <xacro:property name="lidar_radius" value="0.025" />
  <xacro:property name="lidar_height" value="0.05" />
  <xacro:property name="lidar_mass" value="0.05" />

  <!-- cylinder_inertia -->
  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
              iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
              izz="${m*r*r/2}" /> 
  </xacro:macro>
  <!--box_inertia-->
  <!--sphere_inertia-->

  <xacro:macro name="wheel" params="lr parent dir z_offset roll"> <!-- lr: left, right -->
    <link name="${lr}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0 " /> 
        <geometry>
          <!-- <cylinder length="${wheel_height}" radius="${wheel_radius}" /> -->
          <mesh filename="package://staggerlite_description/meshes/wheel.stl"/>
        </geometry>
        <material name="Black" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0 " />
        <geometry>
          <cylinder length="${wheel_height}" radius="${wheel_radius}" />
        </geometry>
      </collision>
      <inertial>
        <mass value="${wheel_mass}" />
        <origin xyz="0 0 0" />
        <xacro:cylinder_inertia  m="${wheel_mass}" r="${wheel_radius}" h="${wheel_height}" />
      </inertial>
    </link>

    <joint name="${lr}_wheel_joint" type="continuous">
      <parent link="${parent}"/>
      <child link="${lr}_wheel_link"/>
      <origin xyz="0 ${dir * wheel_spacing / 2} ${z_offset}" rpy="${roll} 0 0" /> 
      <axis xyz="0 0 1" rpy="0 0 0" />
      <limit effort="100" velocity="100"/>
      <joint_properties damping="0.0" friction="0.0"/>
    </joint>

    <!-- Transmission is important to link the joints and the controller -->
    <!-- <transmission name="${lr}_wheel_joint_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${lr}_wheel_joint" />
      <actuator name="${lr}_wheel_joint_motor">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission> -->

  </xacro:macro>

</robot>